### ISSUE TITLE
spades assembly 

### ISSUE THREAD

**Issue by alexkeeley** [sheffield-bioinformatics-core/microbial-pipeline#4]
There is another error occuring that I think is due to permission issues in creating temp files. This time in spades program 

I'm working on terminal from an interactive node, using qsub: 

My script is getting stuck at this step
singularity exec /usr/local/community/Florey/singularity/microbial-pipeline.simg spades.py -k 21,33,55,77 --pe1-1 ${samp}_L001_R1_001_paired.fastq.gz  --pe1-2 ${samp}_L001_R2_001_paired.fastq.gz --careful -o $samp

Here is the error message from the qsub log:

======= SPAdes pipeline started. Log can be found here: /shared/desilva_group1/Shared/Alex/projects/spyderm_Saureus_analysis/data/practice_fastq/Pairedreads/SW165J-B_S28/spades.log

===== Read error correction started. 

[Errno 1] Operation not permitted: '/shared/desilva_group1/Shared/Alex/projects/spyderm_Saureus_analysis/data/practice_fastq/Pairedreads/SW165J-B_S28/corrected/configs/config.info'
Traceback (most recent call last):
  File "/usr/bin/spades.py", line 797, in main
    ext_python_modules_home, only_compressing_is_needed, log)
  File "/opt/SPAdes-3.13.1-Linux/share/spades/spades_pipeline/hammer_logic.py", line 131, in run_hammer
    dir_util.copy_tree(os.path.join(configs_dir, "hammer"), dst_configs, preserve_times=False)
  File "/usr/lib/python2.7/distutils/dir_util.py", line 167, in copy_tree
    dry_run=dry_run)
  File "/usr/lib/python2.7/distutils/file_util.py", line 165, in copy_file
    os.chmod(dst, S_IMODE(st[ST_MODE]))
OSError: [Errno 1] Operation not permitted: '/shared/desilva_group1/Shared/Alex/projects/spyderm_Saureus_analysis/data/practice_fastq/Pairedreads/SW165J-B_S28/corrected/configs/config.info'

The script then does not proceed further. 

Many thanks for looking into it, 

Alex

**Comment by paul1000ton-coder** [comment]
Good morning.

I was using Spades for a Metagenomic Analysis of my class of pregrade. I had the same problem, I use a subsystem of Linux in Windows. Could you help me please?

Thank you for your time.
